### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by amtg1024** [langegang/planner_project#11]
- Create a new file called index.html inside your project folder.
- Create a new file called styles.css inside folder called css in project folder.
- Include your styles.css file inside the index.html page.
- Create a new Github repo and add, commit and push your files.

- Go through the different Bootstrap components and select the ones that are more similar to your wireframes structure
 
- Add the selected components to your HTML page.
- Implement your Task planner form that contains the required fields:
    Name / Description / AssignedTo / DueDate / Status

**Comment by supotech** [comment]
Reviewed tasks #2. Moving to Done.
